Whq/leiku/WebMemcache/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;

namespace WebMemcache.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(UserInfo user)
        {

            string sql = "select * from UserInfo where UName=@UName and UPwd=@UPwd";
            using (var conn = SqlHelper.Connection)
            {
                 var  loginUser1 = conn.QueryFirstOrDefault<UserInfo>(sql, new  { UName = user.UName, UPwd = user.UPwd });
                var loginUser = SqlMapper.QueryFirstOrDefault<UserInfo>(conn,sql, new  { UName = user.UName, UPwd = user.UPwd });
                if (loginUser == null)
                {
                    return Content("用户名密码错误！");
                }
                else
                {
                    Guid sessionId = Guid.NewGuid();//申请了一个模拟的GUID：SessionId

                    //把sessionid写到客户端浏览器里面去了（一定要把sessionid写到客户端，这样用户在访问其他web资源的时候，就会把cookie中的信息传给服务器，然后通过sessionid的key到Memcached中去取对应的值）
                    Response.Cookies["sessionId"].Value =  sessionId.ToString();

                    //再把用户的信息插入到Memcached中
                    MemcacheHelper.Set(sessionId.ToString(), loginUser, DateTime.Now.AddMinutes(20));
                    return Content("ok");
                }
            }


            //var loginUser = dbContext.UserInfo.Where(u => u.UName.Equals(user.UName) && u.UPwd.Equals(user.UPwd)).FirstOrDefault();

            //if (loginUser == null)
            //{
            //    return Content("用户名密码错误！");
            //}
            //else
            //{
            //    Guid sessionId = Guid.NewGuid();//申请了一个模拟的GUID：SessionId

            //    //把sessionid写到客户端浏览器里面去了（一定要把sessionid写到客户端，这样用户在访问其他web资源的时候，就会把cookie中的信息传给服务器，然后通过sessionid的key到Memcached中去取对应的值）
            //    Response.Cookies["sessionId"].Value = "zs";//sessionId.ToString();

            //    //再把用户的信息插入到Memcached中
            //    MemcacheHelper.Set("zs", loginUser, DateTime.Now.AddMinutes(20));
            //    return Content("ok");
            //}
        }
    }
}

Whq/leiku/WebMemcache/Views/UserLogin/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>

    <script src="../../Scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript">
        if (window.parent.window != window) {
            window.top.location.href = "/Login/Index";
        }


        function changeCheckCode() {
            var newUrl = $("#img").attr("src") + 1;
            $("#img").attr("src", newUrl);
        }


        function afterLogin(data) {
            if (data != "ok") {
                alert(data);
                changeCheckCode();
            } else {
                window.location.href = "/Home/Index";
            }
        }
    </script>


    <style type="text/css">
        * {
            padding: 0;
            margin: 0;
        }

        body {
            text-align: center;
            background: #4974A4;
        }

        #login {
            width: 740px;
            margin: 0 auto;
            font-size: 12px;
        }

        #loginlogo {
            width: 700px;
            height: 100px;
            overflow: hidden;
            background: url('/Content/Images/login/logo.png') no-repeat;
            margin-top: 50px;
        }

        #loginpanel {
            width: 729px;
            position: relative;
            height: 300px;
        }

        .panel-h {
            width: 729px;
            height: 20px;
            background: url('/Content/Images/login/panel-h.gif') no-repeat;
            position: absolute;
            top: 0px;
            left: 0px;
            z-index: 3;
        }

        .panel-f {
            width: 729px;
            height: 13px;
            background: url('/Content/Images/login/panel-f.gif') no-repeat;
            position: absolute;
            bottom: 0px;
            left: 0px;
            z-index: 3;
        }

        .panel-c {
            z-index: 2;
            background: url('/Content/Images/login/panel-c.gif') repeat-y;
            width: 729px;
            height: 300px;
        }

        .panel-c-l {
            position: absolute;
            left: 60px;
            top: 40px;
        }

        .panel-c-r {
            position: absolute;
            right: 20px;
            top: 50px;
            width: 222px;
            line-height: 200%;
            text-align: left;
        }

        .panel-c-l h3 {
            color: #556A85;
            margin-bottom: 10px;
        }

        .panel-c-l td {
            padding: 7px;
        }

        .login-text {
            height: 24px;
            left: 24px;
            border: 1px solid #e9e9e9;
            background: #f9f9f9;
        }

        .login-text-focus {
            border: 1px solid #E6BF73;
        }

        .login-btn {
            width: 114px;
            height: 29px;
            color: #E9FFFF;
            line-height: 29px;
            background: url('/Content/Images/login/login-btn.gif') no-repeat;
            border: none;
            overflow: hidden;
            cursor: pointer;
        }

        #txtUsername, #code, #txtPassword {
            width: 191px;
        }

        #logincopyright {
            text-align: center;
            color: White;
            margin-top: 50px;
        }

        a {
            color: Black;
        }

            a:hover {
                color: Red;
                text-decoration: underline;
            }
    </style>


</head>
<body style="padding: 10px">

    @using (Ajax.BeginForm("Login", "UserLogin", new AjaxOptions() { OnSuccess = "afterLogin" }))
    {

        <div id="login">
            <div id="loginlogo">
            </div>
            <div id="loginpanel">
                <div class="panel-h">
                </div>
                <div class="panel-c">
                    <div class="panel-c-l">

                        <table cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td align="left" colspan="2">
                                        <h3>
                                            请用登录
                                        </h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">
                                        账号：
                                    </td>
                                    <td align="left">
                                        <input type="text" name="UName" value="admin" id="UName" class="login-text" />

                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">
                                        密码：
                                    </td>
                                    <td align="left">
                                        <input type="password" name="UPwd" id="UPwd" value="123" class="login-text" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        验证码：
                                    </td>
                                    <td align="left">
                                        <input type="text" class="login-text" id="code" name="vCode" value="1" />
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <img id="img" onclick="changeCheckCode()" src="/Logon/ValidateCode?id4=1" style="float: left; height: 24px;" />
                                        <div style="float: left; margin-left: 5px; margin-top: 10px;">
                                            <a href="javascript:void(0)" onclick="changeCheckCode();return false;">看不清，换一张</a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" colspan="2">
                                        <input type="submit" id="btnLogin" value="登录" class="login-btn" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="panel-f">
                </div>
            </div>
            <div id="logincopyright">

            </div>
        </div>

    }
</body>
</html>